name: Release

on:
  push:
    tags: [ '**' ]

permissions:
  contents: read

jobs:
  ubuntu:
    uses: 9506hqwy/actions/.github/workflows/go-release-ubuntu.yml@main

  windows:
    uses: 9506hqwy/actions/.github/workflows/go-release-windows.yml@main

  release:

    needs: [ubuntu, windows]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v5

    - uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh config set prompt disabled
        gh release create "${GITHUB_REF_NAME}" ./artifacts/*/*  -t "${GITHUB_REF_NAME}" -d
